language: node_js

node_js:
  - node

script:
  - echo "lofasz"

before_deploy:
  - ./release-notes.sh

deploy:
  - provider: releases
    file: README.md
    release_notes_file: RELEASE_NOTES.md
    prerelease: true
    overwrite: true
    edge: true
    on:
      tags: true